DELETE FROM concert_date_seat;
DELETE FROM concert_date;
DELETE FROM concert;
DELETE FROM queue_token;
DELETE FROM "user";
DELETE FROM point;
DELETE FROM payment;
DELETE FROM reservation;
DELETE FROM config;


ALTER TABLE concert_date_seat ALTER COLUMN id RESTART WITH 1;
ALTER TABLE concert_date ALTER COLUMN id RESTART WITH 1;
ALTER TABLE concert ALTER COLUMN id RESTART WITH 1;
ALTER TABLE queue_token ALTER COLUMN id RESTART WITH 1;
ALTER TABLE "user" ALTER COLUMN id RESTART WITH 1;
ALTER TABLE point ALTER COLUMN id RESTART WITH 1;
ALTER TABLE payment ALTER COLUMN id RESTART WITH 1;
ALTER TABLE reservation ALTER COLUMN id RESTART WITH 1;
ALTER TABLE config ALTER COLUMN id RESTART WITH 1;