SET FOREIGN_KEY_CHECKS = 0;

TRUNCATE TABLE concert_date_seat;
TRUNCATE TABLE concert_date;
TRUNCATE TABLE concert;
TRUNCATE TABLE queue_token;
TRUNCATE TABLE `user`;
TRUNCATE TABLE point;
TRUNCATE TABLE payment;
TRUNCATE TABLE reservation;
TRUNCATE TABLE config;

SET FOREIGN_KEY_CHECKS = 1;